### ISSUE TITLE
Other Losses is not correct

### ISSUE THREAD

**Issue by niklasHagner** [Valish/mma-api#1]
First thing that pops out when reading the README is that the sample data for Jon Jones is incorrect.
He's got 1 total loss loss but it's not categorized as anything. It should be an "other".

`"losses": {
      "total": 1,
      "knockouts": 0,
      "submissions": 0,
      "decisions": 0,
      "others": 0
    }`

The problem is that sherdog-api always returns 0 for that particular field. I've submitted a pull request that fixes the issue

**Comment by benjaminrbarnes** [comment]
Is this still an issue?
