### ISSUE TITLE
Expected behavior when search returns no queries?

### ISSUE THREAD

**Issue by stoicism2323** [Valish/mma-api#2]
Forgive me if this is a dumb question, I am a node noob.

If I query for a fighter and that query returns no links (like query mma.fighter('asdfkjaskdfjaksdjf', function
...), Currently what I get back is a response that shows:

> Error: undefined is not a valid uri or options object.
> at request (/home/username/github/telegram/proj/node_modules/request/index.js:46:11)
> at Object.module.exports.getFighter (/home/username/github/telegram/proj/node_modules/sherdog/lib/sher
> dog/index.js:16:3)
> at /home/username/github/telegram/proj/node_modules/mma/lib/mma/index.js:105:13
> at Request._callback (/home/username/github/telegram/proj/node_modules/google/lib/google.js:85:7)
> at Request.self.callback (/home/username/github/telegram/proj/node_modules/request/request.js:187:22)
> at emitTwo (events.js:106:13)
> at Request.emit (events.js:191:7)
> at Request.<anonymous> (/home/username/github/telegram/proj/node_modules/request/request.js:1044:10)
> at emitOne (events.js:96:13)
> at Request.emit (events.js:188:7)

I'm just not sure if this is the expected behavior or not. Thanks :)

**Comment by valish** [comment]
See #7
